---
title: "Data_Exploration_Classification"
author: "Lisa Beck, Anastasiia Chebatarova, Axel Kandel"
date: "5/22/2019"
output: pdf_document
---

```{r Data Exploration - interest rate vs loan amount}
# plotting the loan amount vs the interest rate
ggplot(data = dataset, mapping = aes(defaulted, loan_amnt)) +
  geom_point()

###
sd <- ds <- plyr::ddply(dataset, "loan_amnt", plyr::summarise, mean = mean(y), sd = sd(y))

ggplot(data = dataset, mapping = aes(defaulted, loan_amnt)) +
    geom_errorbar()

plot(dataset$defaulted, dataset$sub_grade)

```
```{r}
plot(dataset$defaulted, dataset$loan_amnt)
```

```{r Data Exploration - interest rate vs term}
# plotting the loan amount vs the term

plot(data = dataset, term, defaulted)
# Here we can see that the interest rate is generaly higher for 60 months loans and lower for 36 months loans.
```

```{r Data Exploration - interest rate vs grade}
# plotting the loan amount vs the grade

plot(dataset$defaulted, dataset$collection_recovery_fee)
```

```{r Data Exploration - interest rate vs home ownership}
# plotting the loan amount vs home ownership

plot(data = dataset,home_ownership, defaulted)
# Here we can see that the interest rate is generaly higher for 60 months loans and lower for 36 months loans.
```

```{r Data Exploration - interest rate vs verification_status}
# plotting the loan amount vs verification_status

plot(data = dataset,verification_status, defaulted)
# The verification_status seems to also have an influence on the interest rate.

```

```{r Data Exploration - interest rate vs emp_title}
# plotting the loan amount vs verification_status

plot(emp_title, defaulted)
# The verification_status seems to also have an influence on the interest rate.

```